### ISSUE TITLE
Investigate windows resizing/moving on restart

### ISSUE THREAD

**Issue by EJWellman** [EJWellman/QuarmTool#12]
Witnessed in Spell Timers, Map & Mob Info.

Mob Info makes sense to resize since it shrinks/expands.
Look into not shrinking.

**Comment by EJWellman** [comment]
Moving on restart = Not remembering where they were.

**Comment by XDharkonX** [comment]
The overlay window works for me and stays where I put it.  but all of the other windows reload in default positions and sizes when I open the app.  I use 2 monitors on my laptop, not sure if that has anything to do with it.  But the windows will load on whichever monitor I open the app from (opened from taskbar shortcut)

**Comment by EJWellman** [comment]
> But the windows will load on whichever monitor I open the app from (opened from taskbar shortcut)

That sounds like it's a monitor issue.
Does it happen if you open the app, move the windows around, close them (one by one), close the app entirely, then immediately reopen it?

**Comment by XDharkonX** [comment]
Issue still persists for me in [Release 11 - v1.0.9].  I have opened the app, positioned windows and closed individually and they did not retain their size or position on my 2nd monitor.  Its like they revert to default if I place them on the 2nd monitor.  They do retain their positions on the primary monitor though.  Thanks for the work, great project.  I'll dig around and see if I can see why some apps work and retain on an additional monitor and some do not.
Thanks you
