### ISSUE TITLE
Triggers Custom Font Color

### ISSUE THREAD

**Issue by LichLord91** [EJWellman/QuarmTool#17]
This is probably very niche but I change my windows colors using a specialized patching software. This makes certain UI elements difficult to see at times.

Anyway we can add a custom font color option for the spell timers/triggers 

![image](https://github.com/EJWellman/QuarmTool/assets/8435580/bf35dcaf-db03-4740-a0c3-a66688602374)

**Comment by LichLord91** [comment]
Or even change the timer bar colors could be an option

**Comment by LichLord91** [comment]
These colors are pulling from windows built in color panel , using a third party themer that sets these.  Ex.
![image](https://github.com/EJWellman/QuarmTool/assets/8435580/f1aad6d5-21a1-4b2c-a14c-08617d05671f)

**Comment by EJWellman** [comment]
Should be easy enough to make that color adjustable. I'll add it to the pile!
Should be able to get that done this weekend, hopefully.

**Comment by LichLord91** [comment]
Additionally could make a dark mode option? : )

**Comment by EJWellman** [comment]
So, after some work, here's kind of how it looks!
There's a few color categories for the bars, and you can change the text color.
Note that it's one text color, but it does a very slight drop shadow behind it, in the inverted color, to try and give better separation between the text and bar.

I'll be pushing it out in an update soon (sometime tonight, most likely.)

![image](https://github.com/EJWellman/QuarmTool/assets/30203270/66b882a7-ff17-4182-9f50-ba538a98a8eb)

These settings can be found in Settings > Timers (renamed from Triggers), in the collapsed (another new thing! =O ) `Timer Colors` area.

**Comment by LichLord91** [comment]
I like using Dracula Theme for dark mode personally

https://draculatheme.com/contribute

And catppuccin for a light theme

https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md

Both themes strive for great WCAG & ADA standards. 


I incorporated both these themes into my docusaurus wiki long ago and love it.

https://docs.darkisle.rocks/

**Comment by LichLord91** [comment]
Just tested this and its beautiful! Going to play with the colors but this fixed my needs ty ty ty!

![image](https://github.com/EJWellman/QuarmTool/assets/8435580/d4008027-6a61-4779-9114-9e05bc56ca33)
