### ISSUE TITLE
South Qeynos map is South and North Qeynos overlapping

### ISSUE THREAD

**Issue by FeelingMimsy** [EJWellman/QuarmTool#2]
When the selected zone is "qeynos", the map displayed is both the "qeynos" zone map and the "qeynos2" map. This happens whether the zone was detected from the log, or manually chosen from Settings.

**Comment by EJWellman** [comment]
Found where it's occurring. I'm taking a look at it. Should have a fix out for it tomorrow (4/18) evening.

Thanks for the heads up!

**Comment by EJWellman** [comment]
Alright, I lied. It's fixed, and there's a release that fixes it, now! 

[Release v1.0.2](https://github.com/EJWellman/QuarmTool/releases/tag/v1.0.2)
