### ISSUE TITLE
Tracking Window Data

### ISSUE THREAD

**Issue by serrasin** [EJWellman/QuarmTool#28]
When tracking for a rare spawn it can be rough on the eyes to constantly be visually scanning through updated lists of mobs in the track window. Using the Zeal data stream would it be possible to spool the contents of the track window so that audio alerts can be set for specific mob names?

**Comment by EJWellman** [comment]
I don't think that information is being sent, but I'll look into it.

I will say that does stray a little close to automation, which I'm trying to avoid, as it's against the spirit of the server. But I'll talk with Salty and see what he thinks.

**Comment by EJWellman** [comment]
Gonna have to pass on this one.

1. I think it strays way too close to automation, unfortunately.
2. That info isn't being passed currently.
3. Secrets actually explicitly said no to this.

As a Ranger, I agree that the tracking window sucks to look through, but this goes a bit too far.
