### ISSUE TITLE
Suggestion: Create a "Reconnect Zeal Pipes" action

### ISSUE THREAD

**Issue by abigtoe22** [EJWellman/QuarmTool#36]
When my eqgame.exe crashes, I find that I have to exit QuarmTool and restart it to get the Zeal pipe functionality working again. If there would be a way to make the tool look for the named pipes from a new instance of eqgame/zeal without restarting that would be great!

**Comment by EJWellman** [comment]
It *should* be doing that, but I'll take a closer look at it.

**Comment by abigtoe22** [comment]
I haven't had an issue with this in a very long time. I think this is working as intended now.
