### ISSUE TITLE
Suggestion: Minimize all windows option on taskbar menu

### ISSUE THREAD

**Issue by chiefscott** [EJWellman/QuarmTool#37]
An option to minimize all windows would be fantastic in the right click menu on the task bar.

**Comment by EJWellman** [comment]
Ooh, I'll see about getting this added.

**Comment by chiefscott** [comment]
Awesome! Please also add an option to restore when that function is used as well!

**Comment by EJWellman** [comment]
Yeah, if I can get it working, it'll be a toggle.

**Comment by EJWellman** [comment]
I'm going to merge this suggestion with #33, just so that it's easier to keep them in mind when working on each other.
It's gonna take a bit to get to it, as I've got to figure a couple things out.
