### ISSUE TITLE
Suggestion: Mob Respawn Timers that appear at the mobs spawn point instead of where they died.

### ISSUE THREAD

**Issue by cmarabate** [EJWellman/QuarmTool#39]
I love the map feature and have noticed that it even adds little spawn timers every time we kill a mob. But sadly that is not super useful except maybe for the puller and only if they manually move the timer back to where he pulled it from on the map after each kill. 

Because with a group that stays in one spot and has a puller pull all the mobs to that spot, all the timers pile up in the same spot.

If it is possible to have it place the spawn timers at each mob's spawn point instead of where they die, it would be much more useful and way easier for pullers.

Thanks!

**Comment by EJWellman** [comment]
I wish I could, but I have no way of knowing where each mob came from, or what it's home position is, so there's not really a way to do it, unfortunately.
