### ISSUE TITLE
Mob Info: Increase height of Known Loot based on the height of the window

### ISSUE THREAD

**Issue by cmarabate** [EJWellman/QuarmTool#40]
Right now if I increase the height of the Mob Info window, all it does it add a bunch of empty space below all the info. I would like to be able to increase the height of the Known Loot input so I can see it all at once without having to scroll through it.

**Comment by EJWellman** [comment]
Should be easy enough! Look for this in the next release (after 1.1.5)!

**Comment by EJWellman** [comment]
Yeah, this is done, and will be in the next release.
Merch and Loot will both expand to fill the window (with a small margin) if you stretch it.
