### ISSUE TITLE
Kill/Death Timers are incorrect in the latest version

### ISSUE THREAD

**Issue by irefuse** [EJWellman/QuarmTool#44]
At least for the BBM Guards, these kill timers are very short and inaccurate. 

![image](https://github.com/user-attachments/assets/35882a57-7e31-483b-bb87-814ea15181c5)

**Comment by EJWellman** [comment]
I've noticed this on some mobs.
I need to look into it, it's on my radar.

**Comment by EJWellman** [comment]
Found it. This'll be fixed in the next release.
