### ISSUE TITLE
Mob info window size resets

### ISSUE THREAD

**Issue by Kossorri** [EJWellman/QuarmTool#45]
I resized the mob info window but it keeps resetting back to the default size when the mob info window is closed and reopened. Can we get this to save the sized settings?

**Comment by EJWellman** [comment]
I should be able to make that an option yeah.

**Comment by EJWellman** [comment]
This'll be in the next release, the code is done. 
![image](https://github.com/user-attachments/assets/c2cab9d0-b3ee-4b72-85f2-7efba4f22b1f)
