### ISSUE TITLE
Suggestion: Trigger for Tells

### ISSUE THREAD

**Issue by Hiethen** [EJWellman/QuarmTool#48]
I'm not sure if this is already doable, but would it be possible to get a trigger for /tells.

**Comment by EJWellman** [comment]
![image](https://github.com/user-attachments/assets/06c9437c-6853-40d5-b0ae-a6ef563c48c8)
This will work as part of the overlay.
This includes one for receiving tells, and for guild messages (pick whichever you need).

`(\w+)\stells\syou\,`
`(\w+)\stells\sthe\sguild\,`

**Comment by Hiethen** [comment]
Could it possibly be added to the Pre-Built triggers in the future?

**Comment by Hiethen** [comment]
I tried this and it fires off when talking to NPCs.
