### ISSUE TITLE
Add 5 min mod rod custom timer to triggers

### ISSUE THREAD

**Issue by Celedh** [EJWellman/QuarmTool#8]
Add 5 min mod rod custom timer to triggers

**Comment by EJWellman** [comment]
Coming in the next update!
![image](https://github.com/EJWellman/QuarmTool/assets/30203270/d7c2958c-fc66-47b6-83e6-38d31bb53ea9)

**Comment by EJWellman** [comment]
Added in https://github.com/EJWellman/QuarmTool/releases/tag/v1.0.10
